# Generated by Django 4.1.5 on 2023-02-11 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membersApp', '0002_members_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('channel_id', models.CharField(max_length=250)),
                ('channel_secret', models.CharField(max_length=250)),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_api_data', to='membersApp.members')),
            ],
        ),
    ]
