# Generated by Django 4.1.5 on 2023-02-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('picture', models.TextField()),
            ],
        ),
    ]
