# Generated by Django 4.1.5 on 2023-02-14 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membersApp', '0002_members_url'),
        ('lineApp', '0002_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='members',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='line_customer_data', to='membersApp.members'),
            preserve_default=False,
        ),
    ]
