# Generated by Django 4.1.5 on 2023-03-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineApp', '0003_customers_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='user_id',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
