# Generated by Django 4.1.5 on 2023-02-27 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membersApp', '0002_members_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_interval_category', models.CharField(max_length=150)),
                ('begin_time', models.CharField(max_length=150)),
                ('end_time', models.CharField(max_length=150)),
                ('begin_date', models.CharField(max_length=150)),
                ('end_date', models.CharField(max_length=150)),
                ('time_slice', models.CharField(max_length=50)),
                ('time_slice_unit', models.CharField(max_length=10)),
                ('pre_ordering_numbers', models.CharField(max_length=15)),
                ('pre_ordering_unit', models.CharField(max_length=15)),
                ('time_id', models.CharField(max_length=150, unique=True)),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_setting', to='membersApp.members')),
            ],
        ),
        migrations.CreateModel(
            name='Time_pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_price', models.CharField(max_length=100)),
                ('discount_price', models.CharField(max_length=100)),
                ('discount_begin_date', models.CharField(max_length=100)),
                ('discount_end_date', models.CharField(max_length=100)),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_pricing', to='membersApp.members')),
                ('time_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_pricing', to='calendarApp.time_setting', to_field='time_id')),
            ],
        ),
    ]
