# Generated by Django 4.1.5 on 2023-02-27 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time_setting',
            name='pre_ordering_numbers',
        ),
        migrations.RemoveField(
            model_name='time_setting',
            name='pre_ordering_unit',
        ),
    ]
