# Generated by Django 4.1.5 on 2023-01-29 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_audit_cancel',
            name='members',
        ),
        migrations.RemoveField(
            model_name='pay_deposit',
            name='members',
        ),
        migrations.RemoveField(
            model_name='time_pricing',
            name='members',
        ),
        migrations.RemoveField(
            model_name='time_setting',
            name='members',
        ),
    ]
