# Generated by Django 4.1.5 on 2023-02-27 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0002_remove_time_setting_pre_ordering_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_pricing',
            name='time_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_pricing', to='calendarApp.time_setting'),
        ),
        migrations.AlterField(
            model_name='time_setting',
            name='time_id',
            field=models.CharField(max_length=150),
        ),
    ]
