# Generated by Django 4.1.5 on 2023-02-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0004_time_setting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_pricing',
            name='status',
            field=models.CharField(default='launch', max_length=100),
            preserve_default=False,
        ),
    ]
