# Generated by Django 4.1.5 on 2023-02-12 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lineApp', '0002_customers'),
        ('membersApp', '0002_members_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=150)),
                ('booking_date', models.CharField(max_length=150)),
                ('booking_time', models.CharField(max_length=50)),
                ('booking_total_time', models.CharField(max_length=50)),
                ('booking_price', models.CharField(max_length=50)),
                ('booking_status', models.CharField(max_length=15)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='lineApp.customers')),
                ('members_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='membersApp.members')),
            ],
        ),
    ]
