# Generated by Django 4.1.5 on 2023-02-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
