# Generated by Django 4.1.5 on 2023-02-17 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartApp', '0002_alter_booking_booking_id'),
        ('orderApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bookings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cartApp.booking', to_field='booking_id'),
        ),
    ]
