# Generated by Django 4.1.5 on 2023-03-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0002_alter_order_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(max_length=100),
        ),
    ]
