# Generated by Django 4.1.5 on 2023-02-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='url',
            field=models.CharField(default='/calendar/views/test', max_length=150),
            preserve_default=False,
        ),
    ]
